### ISSUE TITLE
problem of date wise stats in Admin BP 

### ISSUE THREAD

**Issue by akritii-3107** [bantu-4879/soft-engg-project-jan-2024-se-jan-2#7]
`                    # n_tickets_today = sum(
                    #     [
                    #         1
                    #         for ts in ticket_creation_timestamp_list
                    #         if current_timestamp >= ts >= this_day_start_timestamp
                    #     ]
                    # )
                    # n_tickets_week = sum(
                    #     [
                    #         1
                    #         for ts in ticket_creation_timestamp_list
                    #         if current_timestamp >= ts >= this_week_start_timestamp
                    #     ]
                    # )
                    # n_tickets_month = sum(
                    #     [
                    #         1
                    #         for ts in ticket_creation_timestamp_list
                    #         if current_timestamp >= ts >= this_month_start_timestamp
                    #     ]
                    # )`

in admin.bp file due to datetime function there is some issue.

**Comment by sahithid** [comment]
Fixed the issue using stats_bp from the backend.
